"""
Django settings for studentcorner project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# ==================== DJANGO SETTINGS.PY ====================
# This is the CONFIGURATION FILE for the entire Django project
# All project settings are defined here
#
# FILE LOCATION: studentcorner/studentcorner/settings.py
# THIS CONTROLS:
# - Database configuration
# - Installed apps
# - Security settings
# - Static files location
# - Middleware
# - Templates
#
# CONNECTION:
# settings.py → Loaded when Django starts → Affects entire project

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = project root directory (where manage.py is located)
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# ==================== SECURITY SETTINGS ====================
# SECRET_KEY: Used for cryptographic signing (sessions, CSRF tokens)
# WARNING: Keep this secret! Never share in production
SECRET_KEY = 'django-insecure-#eot=*j6f4v^gfjmn41iq-8j)x@q5g_yaw#o$3s#m7w+4w8rz0'

# DEBUG: Turns on debug mode (detailed error pages)
# TRUE = Development mode (detailed errors, auto-reload)
# FALSE = Production mode (generic error page, better security)
DEBUG = True

# ALLOWED_HOSTS: Which domains can access this app
# Empty [] = localhost only (for development)
# ['*'] = Allow all domains (NOT SAFE for production)
# Production: ['yourdomain.com', 'www.yourdomain.com']
ALLOWED_HOSTS = []


# ==================== INSTALLED APPS ====================
# List of all apps (features) enabled in this Django project
# Django reads this list and activates each app
# YOUR APPS: 'grades' and 'circluars' (must be added here to use them)
#
# Django Built-in Apps:
#   - admin: Admin panel interface
#   - auth: User authentication system
#   - contenttypes: Track models across apps
#   - sessions: Session management
#   - messages: Flash messages for users
#   - staticfiles: Manage CSS, JS, images
#
# Custom Apps:
#   - grades: Student grades app
#   - circluars: College circulars app

INSTALLED_APPS = [
    'django.contrib.admin',        # Admin panel
    'django.contrib.auth',         # Authentication
    'django.contrib.contenttypes', # Content types
    'django.contrib.sessions',     # Session management
    'django.contrib.messages',     # Messaging system
    'django.contrib.staticfiles',  # Static files (CSS, JS)
    'grades',                      # YOUR APP 1
    'circluars',                   # YOUR APP 2
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ROOT_URLCONF: Points to the main urls.py file
# This tells Django where to find URL routing configuration
# 'studentcorner.urls' = Look in studentcorner/urls.py for URL patterns
ROOT_URLCONF = 'studentcorner.urls'

# ==================== TEMPLATES CONFIGURATION ====================
# Where Django looks for HTML templates
# Templates are HTML files with Django template tags {{ }} and {% %}
#
# 'DIRS': [] = Empty (look in app directories)
# 'APP_DIRS': True = Look in each app's templates/ folder
#
# Example: Django finds templates at:
#   grades/templates/home.html
#   grades/templates/marksheet.html
#   circluars/templates/index.html

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],                    # Additional template directories (empty for now)
        'APP_DIRS': True,              # Look in apps/templates/ folders
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',    # Access request object
                'django.contrib.auth.context_processors.auth',   # Access user/auth info
                'django.contrib.messages.context_processors.messages',  # Access messages
            ],
        },
    },
]

WSGI_APPLICATION = 'studentcorner.wsgi.application'


# ==================== DATABASE CONFIGURATION ====================
# Defines which database to use and where it's located
#
# Database Type: SQLite3 (lightweight, file-based)
#   - Perfect for development and small projects
#   - Data stored in: db.sqlite3 file
#   - No separate database server needed
#
# Grade model data stored in: db.sqlite3 with table name: grades_grade
#
# Production: Change to PostgreSQL, MySQL, etc.

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # Database type
        'NAME': BASE_DIR / 'db.sqlite3',         # File location
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
